# Adult Dataset (Census Bureau)
Operations: Subset, Merge, Sort, Transpose, Melt, Pivot

In [1]:
import pandas as pd

## Load Dataset (Fix No Header)

In [2]:
df = pd.read_csv("../DSBDALExam DataSets/Adult/adult.csv", header=None)

df.columns = [
    'age', 'workclass', 'fnlwgt', 'education', 'education-num',
    'marital-status', 'occupation', 'relationship', 'race', 'sex',
    'capital-gain', 'capital-loss', 'hours-per-week',
    'native-country', 'income'
]

df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64
 11  capital-loss    32561 non-null  int64
 12  hours-per-week  32561 non-null  int64
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

## s. Create subsets

In [4]:
country_df = df[df['native-country'] == 'United-States']
male_df = df[df['sex'] == 'Male']
race_df = df[df['race'] == 'White']

country_df.head(), male_df.head(), race_df.head()

(Empty DataFrame
 Columns: [age, workclass, fnlwgt, education, education-num, marital-status, occupation, relationship, race, sex, capital-gain, capital-loss, hours-per-week, native-country, income]
 Index: [],
 Empty DataFrame
 Columns: [age, workclass, fnlwgt, education, education-num, marital-status, occupation, relationship, race, sex, capital-gain, capital-loss, hours-per-week, native-country, income]
 Index: [],
 Empty DataFrame
 Columns: [age, workclass, fnlwgt, education, education-num, marital-status, occupation, relationship, race, sex, capital-gain, capital-loss, hours-per-week, native-country, income]
 Index: [])

## t. Merge subsets

In [5]:
merged_df = pd.concat([male_df, race_df])
merged_df.head()

Empty DataFrame
Columns: [age, workclass, fnlwgt, education, education-num, marital-status, occupation, relationship, race, sex, capital-gain, capital-loss, hours-per-week, native-country, income]
Index: []

## u. Sort Data

In [6]:
sorted_df = df.sort_values(by='hours-per-week', ascending=False)
sorted_df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
25354,65,Private,89681,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,99,United-States,<=50K
29751,51,Self-emp-not-inc,32372,12th,8,Married-civ-spouse,Other-service,Husband,White,Male,0,0,99,United-States,<=50K
8796,39,Private,70995,Bachelors,13,Married-civ-spouse,Transport-moving,Husband,White,Male,15024,0,99,United-States,>50K
21147,39,Private,348521,Some-college,10,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,2415,99,United-States,>50K
25806,49,?,31478,7th-8th,4,Married-civ-spouse,?,Husband,White,Male,0,0,99,United-States,<=50K

## v. Transpose

In [ ]:
transpose_df = df.T
transpose_df.head()

,0,1,2,3,4,5,6,7,8,9,...,32551,32552,32553,32554,32555,32556,32557,32558,32559,32560
age,39,50,38,53,28,37,49,52,31,42,...,32,43,32,53,22,27,40,58,22,52
workclass,State-gov,Self-emp-not-inc,Private,Private,Private,Private,Private,Self-emp-not-inc,Private,Private,...,Private,Private,Private,Private,Private,Private,Private,Private,Private,Self-emp-inc
fnlwgt,77516,83311,215646,234721,338409,284582,160187,209642,45781,159449,...,34066,84661,116138,321865,310152,257302,154374,151910,201490,287927
education,Bachelors,Bachelors,HS-grad,11th,Bachelors,Masters,9th,HS-grad,Masters,Bachelors,...,10th,Assoc-voc,Masters,Masters,Some-college,Assoc-acdm,HS-grad,HS-grad,HS-grad,HS-grad
education-num,13,13,9,7,13,14,5,9,14,13,...,6,11,14,14,10,12,9,9,9,9

## w. Melt

In [8]:
melted_df = pd.melt(
    df,
    id_vars=['sex'],
    value_vars=['age', 'hours-per-week', 'education-num'],
    var_name='Feature',
    value_name='Value'
)

melted_df.head()

       sex Feature  Value
0     Male     age     39
1     Male     age     50
2     Male     age     38
3     Male     age     53
4   Female     age     28

## x. Pivot

In [9]:
wide_df = melted_df.pivot_table(
    index='sex',
    columns='Feature',
    values='Value',
    aggfunc='mean'
)

wide_df

Feature        age  education-num  hours-per-week
sex
Female   36.858230      10.035744       36.410361
Male     39.433547      10.102891       42.428086

## Conclusion
- Subsets created using country, sex, race
- Merged using concat
- Sorted using working hours
- Data reshaped using transpose, melt, pivot